version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.15
    working_directory: /project
    steps:
      - checkout
      - run: make build
      - run: make test

  checks:
    docker:
      - image: golang:1.15
    steps:
      - checkout
      - run: make install-lint
      - run: make check-modtidy
      - run: make lint
      - run: make build

  integration:
    docker:
      - image: golang:1.15
      - image: circleci/postgres:13
        environment:
          PGPORT: 5433
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgrespassword
    steps:
      - checkout
      - run:
          name: "Prebuild"
          command: |
            echo "Prebuild..."
      - run:
          name: "Launch background processes"
          background: true
          command: |
            echo "Starting executables we need in background"
      - run:
          name: "Give time for processes to start"
          command: sleep 3
      - run:
          name: "Run integration tests"
          command: |
            make test-integration

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - checks
      - integration:
          requires:
            - build
            - checks
