version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.16
    working_directory: /project
    steps:
      - checkout
      - run: make build
      - run: make test

  checks:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run: make install-lint
      - run: make check-modtidy
      - run: make lint
      - run: make build

  integration:
    machine:
      image: ubuntu-2004:202104-01 
    steps:
      - checkout
      - run:
          name: "Run database tests"
          command: |
            make test-database-services

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - checks
      - integration:
          requires:
            - build
            - checks
