version: "3.9"
networks:
  mongo:
    driver: bridge
services:
  mongodb:
    image: mongo:latest
    logging:
      driver: none
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password

  goapp:
    image: golang:latest
    networks:
      - mongo
    volumes:
      - ./../:/app
    working_dir: /app
    environment:
      MONGO_URI: mongodb://mongo:password@mongodb:27017/
    entrypoint: ["make", "test-mongo"]
