name: Build jobs

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: Build
        run: |
          make build

  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - run: make build
      - name: ModTidy check
        run: make check-modtidy
      - name: Fmt check
        run: make fmt-check
      - name: Lint check
        run: |
          make install_lint
          make lint

  tests-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: "Launch db engine in background"
        run: |
          make test-database-up
      - name: "Give time for processes to start"
        run: sleep 5
      - name: Components tests
        run:  make test-components

  tests-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: "Launch db engine in background"
        run: |
          make test-database-up
      - name: "Give time for processes to start"
        run: sleep 5
      - name: Integration test
        run:  make test-integration
